# Generated by Django 3.2.16 on 2023-05-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230517_0353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
